import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "fr" | "ar" | "zh" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.symptomChecker": "Symptom Checker",
    "nav.aiDoctor": "AI Doctor",
    "nav.healthLibrary": "Health Library",
    "nav.about": "About",
    "nav.login": "Login",
    "nav.getStarted": "Get Started",
    // Hero
    "hero.badge": "AI-Powered Health Intelligence",
    "hero.title1": "Your Health,",
    "hero.title2": "Decoded",
    "hero.title3": "by AI",
    "hero.subtitle": "Check symptoms, chat with an AI doctor, and take control of your wellness — all from the comfort of your home. Instant, accurate, and always available.",
    "hero.checkSymptoms": "Check Symptoms Now",
    "hero.talkAI": "Talk to AI Doctor",
    // Stats
    "stats.healthChecks": "Health Checks",
    "stats.accuracy": "Accuracy Rate",
    "stats.users": "Happy Users",
    "stats.available": "Available",
    // Features
    "features.title1": "Everything You Need for",
    "features.title2": "Better Health",
    "features.subtitle": "Powered by cutting-edge AI and backed by medical research",
    "features.aiSymptom": "AI Symptom Analysis",
    "features.aiSymptomDesc": "Advanced AI analyzes your symptoms using medical databases to provide accurate health insights.",
    "features.aiChat": "24/7 AI Doctor Chat",
    "features.aiChatDesc": "Chat with our AI health assistant anytime. Get instant answers to your health questions.",
    "features.monitoring": "Health Monitoring",
    "features.monitoringDesc": "Track your health metrics over time and receive personalized wellness recommendations.",
    "features.security": "Private & Secure",
    "features.securityDesc": "Your health data is encrypted end-to-end. We never share your information with third parties.",
    "features.instant": "Instant Results",
    "features.instantDesc": "Get health assessments in seconds, not hours. No waiting rooms or appointments needed.",
    "features.family": "Family Health Hub",
    "features.familyDesc": "Manage health profiles for your entire family from a single, intuitive dashboard.",
    // How it works
    "how.title": "How",
    "how.works": "Works",
    "how.subtitle": "Three simple steps to better health understanding",
    "how.step1": "Describe Symptoms",
    "how.step1Desc": "Select or type your symptoms into our intelligent checker",
    "how.step2": "AI Analysis",
    "how.step2Desc": "Our AI cross-references millions of medical data points",
    "how.step3": "Get Insights",
    "how.step3Desc": "Receive personalized health insights and next steps",
    // Testimonials
    "testimonials.title": "Loved by",
    "testimonials.highlight": "Millions",
    // CTA
    "cta.title": "Start Your Health Journey Today",
    "cta.subtitle": "Join 500,000+ people who trust AIDoc for their health insights.",
    "cta.button": "Create Free Account",
    // Symptom Checker
    "symptom.title": "AI",
    "symptom.titleHighlight": "Symptom",
    "symptom.titleEnd": "Checker",
    "symptom.subtitle": "Select your symptoms and let our AI analyze potential conditions",
    "symptom.search": "Search symptoms...",
    "symptom.analyze": "Analyze with AI",
    "symptom.analyzing": "Analyzing Symptoms...",
    "symptom.results": "AI Analysis Results",
    "symptom.disclaimer": "This is an AI-generated assessment and not a medical diagnosis. Always consult a healthcare professional for medical advice.",
    // AI Chat
    "chat.title": "AI Health Assistant",
    "chat.online": "Online • Powered by AI",
    "chat.welcome": "Hello! 👋 I'm your **AI Health Assistant**. I can help you understand symptoms, provide health tips, and guide you on when to seek medical care.\n\n*How can I help you today?*",
    "chat.quickQuestions": "Quick questions",
    "chat.placeholder": "Describe your symptoms or ask a health question...",
    "chat.disclaimer": "⚠️ AI responses are informational only. Always consult a healthcare professional.",
    // Health Library
    "library.title": "Health",
    "library.titleHighlight": "Library",
    "library.subtitle": "Evidence-based health articles curated by medical professionals",
    "library.search": "Search articles...",
    "library.noResults": "No articles found. Try a different search or category.",
    // About
    "about.title": "About",
    "about.subtitle": "We're on a mission to make healthcare accessible, understandable, and proactive for everyone.",
    "about.missionTitle": "Our Mission",
    "about.missionText": "AIDoc combines cutting-edge artificial intelligence with medical expertise to provide instant, reliable health insights. We believe everyone deserves access to quality healthcare guidance, regardless of location, time, or resources.",
    "about.valuesTitle": "Our",
    "about.valuesHighlight": "Values",
    "about.teamTitle": "Meet the",
    "about.teamHighlight": "Team",
    // Auth
    "auth.signIn": "Sign In",
    "auth.signInSubtitle": "Enter your credentials to access your account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.createOne": "Create one",
    "auth.createAccount": "Create Account",
    "auth.createSubtitle": "Start your free health journey with AIDoc",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.hasAccount": "Already have an account?",
    "auth.signInLink": "Sign in",
    "auth.resetPassword": "Reset Password",
    "auth.resetSubtitle": "Enter your email and we'll send you a reset link",
    "auth.sendResetLink": "Send Reset Link",
    "auth.checkEmail": "Check Your Email",
    "auth.resetSent": "We've sent a password reset link to your email address. Please check your inbox.",
    "auth.backToLogin": "Back to login",
    "auth.welcomeBack": "Welcome Back to AIDoc",
    "auth.welcomeBackSubtitle": "Your AI health companion is ready to assist you with personalized health insights.",
    "auth.joinTitle": "Join AIDoc Today",
    "auth.joinSubtitle": "Get AI-powered health insights, 24/7 symptom checking, and personalized wellness guidance.",
    // Footer
    "footer.description": "Your AI-powered health companion. Get instant symptom analysis and personalized health guidance.",
    "footer.quickLinks": "Quick Links",
    "footer.legal": "Legal",
    "footer.contact": "Contact",
    "footer.rights": "© 2026 AIDoc. All rights reserved.",
    "footer.disclaimer": "⚠️ AIDoc is not a substitute for professional medical advice.",
    // Admin
    "admin.dashboard": "Dashboard",
    "admin.welcome": "Welcome back, Admin",
    "admin.totalUsers": "Total Users",
    "admin.healthChecksToday": "Health Checks Today",
    "admin.aiChatSessions": "AI Chat Sessions",
    "admin.criticalAlerts": "Critical Alerts",
    "admin.users": "Users",
    "admin.aiChats": "AI Chats",
    "admin.backToSite": "Back to Site",
  },
  es: {
    "nav.home": "Inicio",
    "nav.symptomChecker": "Verificador de Síntomas",
    "nav.aiDoctor": "Doctor IA",
    "nav.healthLibrary": "Biblioteca de Salud",
    "nav.about": "Acerca de",
    "nav.login": "Iniciar Sesión",
    "nav.getStarted": "Comenzar",
    "hero.badge": "Inteligencia de Salud con IA",
    "hero.title1": "Tu Salud,",
    "hero.title2": "Decodificada",
    "hero.title3": "por IA",
    "hero.subtitle": "Verifica síntomas, chatea con un doctor IA y toma el control de tu bienestar — todo desde la comodidad de tu hogar.",
    "hero.checkSymptoms": "Verificar Síntomas",
    "hero.talkAI": "Hablar con Doctor IA",
    "stats.healthChecks": "Chequeos de Salud",
    "stats.accuracy": "Tasa de Precisión",
    "stats.users": "Usuarios Felices",
    "stats.available": "Disponible",
    "features.title1": "Todo lo que Necesitas para",
    "features.title2": "Mejor Salud",
    "features.subtitle": "Impulsado por IA de vanguardia y respaldado por investigación médica",
    "features.aiSymptom": "Análisis de Síntomas con IA",
    "features.aiSymptomDesc": "La IA avanzada analiza tus síntomas usando bases de datos médicas.",
    "features.aiChat": "Chat Doctor IA 24/7",
    "features.aiChatDesc": "Chatea con nuestro asistente de salud IA en cualquier momento.",
    "features.monitoring": "Monitoreo de Salud",
    "features.monitoringDesc": "Rastrea tus métricas de salud y recibe recomendaciones personalizadas.",
    "features.security": "Privado y Seguro",
    "features.securityDesc": "Tus datos de salud están encriptados de extremo a extremo.",
    "features.instant": "Resultados Instantáneos",
    "features.instantDesc": "Obtén evaluaciones de salud en segundos, no horas.",
    "features.family": "Hub de Salud Familiar",
    "features.familyDesc": "Gestiona los perfiles de salud de toda tu familia.",
    "how.title": "Cómo",
    "how.works": "Funciona",
    "how.subtitle": "Tres pasos simples para entender mejor tu salud",
    "how.step1": "Describe Síntomas",
    "how.step1Desc": "Selecciona o escribe tus síntomas",
    "how.step2": "Análisis IA",
    "how.step2Desc": "Nuestra IA cruza millones de datos médicos",
    "how.step3": "Obtén Insights",
    "how.step3Desc": "Recibe información personalizada y próximos pasos",
    "testimonials.title": "Amado por",
    "testimonials.highlight": "Millones",
    "cta.title": "Comienza Tu Viaje de Salud Hoy",
    "cta.subtitle": "Únete a más de 500,000 personas que confían en AIDoc.",
    "cta.button": "Crear Cuenta Gratis",
    "symptom.title": "Verificador de",
    "symptom.titleHighlight": "Síntomas",
    "symptom.titleEnd": "con IA",
    "symptom.subtitle": "Selecciona tus síntomas y deja que nuestra IA analice condiciones potenciales",
    "symptom.search": "Buscar síntomas...",
    "symptom.analyze": "Analizar con IA",
    "symptom.analyzing": "Analizando Síntomas...",
    "symptom.results": "Resultados del Análisis IA",
    "symptom.disclaimer": "Esta es una evaluación generada por IA y no un diagnóstico médico.",
    "chat.title": "Asistente de Salud IA",
    "chat.online": "En línea • Impulsado por IA",
    "chat.welcome": "¡Hola! 👋 Soy tu **Asistente de Salud IA**. Puedo ayudarte a entender síntomas y brindarte consejos de salud.\n\n*¿Cómo puedo ayudarte hoy?*",
    "chat.quickQuestions": "Preguntas rápidas",
    "chat.placeholder": "Describe tus síntomas o haz una pregunta de salud...",
    "chat.disclaimer": "⚠️ Las respuestas de IA son solo informativas. Siempre consulta a un profesional de salud.",
    "library.title": "Biblioteca de",
    "library.titleHighlight": "Salud",
    "library.subtitle": "Artículos de salud basados en evidencia",
    "library.search": "Buscar artículos...",
    "library.noResults": "No se encontraron artículos.",
    "about.title": "Acerca de",
    "about.subtitle": "Nuestra misión es hacer la atención médica accesible para todos.",
    "about.missionTitle": "Nuestra Misión",
    "about.missionText": "AIDoc combina inteligencia artificial con experiencia médica para brindar información de salud confiable.",
    "about.valuesTitle": "Nuestros",
    "about.valuesHighlight": "Valores",
    "about.teamTitle": "Conoce al",
    "about.teamHighlight": "Equipo",
    "auth.signIn": "Iniciar Sesión",
    "auth.signInSubtitle": "Ingresa tus credenciales para acceder a tu cuenta",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.createOne": "Crear una",
    "auth.createAccount": "Crear Cuenta",
    "auth.createSubtitle": "Comienza tu viaje de salud gratis con AIDoc",
    "auth.firstName": "Nombre",
    "auth.lastName": "Apellido",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "auth.signInLink": "Iniciar sesión",
    "auth.resetPassword": "Restablecer Contraseña",
    "auth.resetSubtitle": "Ingresa tu correo y te enviaremos un enlace",
    "auth.sendResetLink": "Enviar Enlace",
    "auth.checkEmail": "Revisa Tu Correo",
    "auth.resetSent": "Hemos enviado un enlace de restablecimiento a tu correo.",
    "auth.backToLogin": "Volver al inicio de sesión",
    "auth.welcomeBack": "Bienvenido de Nuevo a AIDoc",
    "auth.welcomeBackSubtitle": "Tu compañero de salud IA está listo para asistirte.",
    "auth.joinTitle": "Únete a AIDoc Hoy",
    "auth.joinSubtitle": "Obtén información de salud con IA las 24/7.",
    "footer.description": "Tu compañero de salud con IA.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.legal": "Legal",
    "footer.contact": "Contacto",
    "footer.rights": "© 2026 AIDoc. Todos los derechos reservados.",
    "footer.disclaimer": "⚠️ AIDoc no sustituye el consejo médico profesional.",
    "admin.dashboard": "Panel",
    "admin.welcome": "Bienvenido, Admin",
    "admin.totalUsers": "Usuarios Totales",
    "admin.healthChecksToday": "Chequeos Hoy",
    "admin.aiChatSessions": "Sesiones de Chat IA",
    "admin.criticalAlerts": "Alertas Críticas",
    "admin.users": "Usuarios",
    "admin.aiChats": "Chats IA",
    "admin.backToSite": "Volver al Sitio",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.symptomChecker": "Vérificateur de Symptômes",
    "nav.aiDoctor": "Docteur IA",
    "nav.healthLibrary": "Bibliothèque Santé",
    "nav.about": "À Propos",
    "nav.login": "Connexion",
    "nav.getStarted": "Commencer",
    "hero.badge": "Intelligence Santé par IA",
    "hero.title1": "Votre Santé,",
    "hero.title2": "Décodée",
    "hero.title3": "par l'IA",
    "hero.subtitle": "Vérifiez vos symptômes, consultez un médecin IA et prenez le contrôle de votre bien-être — depuis chez vous.",
    "hero.checkSymptoms": "Vérifier les Symptômes",
    "hero.talkAI": "Parler au Docteur IA",
    "stats.healthChecks": "Bilans de Santé",
    "stats.accuracy": "Taux de Précision",
    "stats.users": "Utilisateurs Satisfaits",
    "stats.available": "Disponible",
    "features.title1": "Tout ce qu'il Faut pour une",
    "features.title2": "Meilleure Santé",
    "features.subtitle": "Propulsé par l'IA de pointe et soutenu par la recherche médicale",
    "features.aiSymptom": "Analyse des Symptômes par IA",
    "features.aiSymptomDesc": "L'IA avancée analyse vos symptômes à l'aide de bases de données médicales.",
    "features.aiChat": "Chat Docteur IA 24/7",
    "features.aiChatDesc": "Consultez notre assistant santé IA à tout moment.",
    "features.monitoring": "Suivi de Santé",
    "features.monitoringDesc": "Suivez vos métriques de santé et recevez des recommandations personnalisées.",
    "features.security": "Privé et Sécurisé",
    "features.securityDesc": "Vos données de santé sont chiffrées de bout en bout.",
    "features.instant": "Résultats Instantanés",
    "features.instantDesc": "Obtenez des évaluations de santé en quelques secondes.",
    "features.family": "Hub Santé Familiale",
    "features.familyDesc": "Gérez les profils de santé de toute votre famille.",
    "how.title": "Comment",
    "how.works": "Fonctionne",
    "how.subtitle": "Trois étapes simples vers une meilleure compréhension de votre santé",
    "how.step1": "Décrivez vos Symptômes",
    "how.step1Desc": "Sélectionnez ou tapez vos symptômes",
    "how.step2": "Analyse IA",
    "how.step2Desc": "Notre IA croise des millions de données médicales",
    "how.step3": "Obtenez des Insights",
    "how.step3Desc": "Recevez des informations personnalisées",
    "testimonials.title": "Aimé par des",
    "testimonials.highlight": "Millions",
    "cta.title": "Commencez Votre Parcours Santé Aujourd'hui",
    "cta.subtitle": "Rejoignez plus de 500 000 personnes qui font confiance à AIDoc.",
    "cta.button": "Créer un Compte Gratuit",
    "symptom.title": "Vérificateur de",
    "symptom.titleHighlight": "Symptômes",
    "symptom.titleEnd": "par IA",
    "symptom.subtitle": "Sélectionnez vos symptômes et laissez notre IA analyser les conditions potentielles",
    "symptom.search": "Rechercher des symptômes...",
    "symptom.analyze": "Analyser avec l'IA",
    "symptom.analyzing": "Analyse en cours...",
    "symptom.results": "Résultats de l'Analyse IA",
    "symptom.disclaimer": "Ceci est une évaluation générée par l'IA, pas un diagnostic médical.",
    "chat.title": "Assistant Santé IA",
    "chat.online": "En ligne • Propulsé par l'IA",
    "chat.welcome": "Bonjour ! 👋 Je suis votre **Assistant Santé IA**. Je peux vous aider à comprendre vos symptômes.\n\n*Comment puis-je vous aider aujourd'hui ?*",
    "chat.quickQuestions": "Questions rapides",
    "chat.placeholder": "Décrivez vos symptômes ou posez une question santé...",
    "chat.disclaimer": "⚠️ Les réponses IA sont uniquement informatives.",
    "library.title": "Bibliothèque de",
    "library.titleHighlight": "Santé",
    "library.subtitle": "Articles de santé fondés sur des preuves",
    "library.search": "Rechercher des articles...",
    "library.noResults": "Aucun article trouvé.",
    "about.title": "À Propos d'",
    "about.subtitle": "Notre mission est de rendre les soins de santé accessibles à tous.",
    "about.missionTitle": "Notre Mission",
    "about.missionText": "AIDoc combine l'intelligence artificielle avec l'expertise médicale pour fournir des informations de santé fiables.",
    "about.valuesTitle": "Nos",
    "about.valuesHighlight": "Valeurs",
    "about.teamTitle": "Rencontrez l'",
    "about.teamHighlight": "Équipe",
    "auth.signIn": "Se Connecter",
    "auth.signInSubtitle": "Entrez vos identifiants pour accéder à votre compte",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.noAccount": "Pas de compte ?",
    "auth.createOne": "Créer un",
    "auth.createAccount": "Créer un Compte",
    "auth.createSubtitle": "Commencez votre parcours santé gratuit avec AIDoc",
    "auth.firstName": "Prénom",
    "auth.lastName": "Nom",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.signInLink": "Se connecter",
    "auth.resetPassword": "Réinitialiser le Mot de Passe",
    "auth.resetSubtitle": "Entrez votre e-mail et nous vous enverrons un lien",
    "auth.sendResetLink": "Envoyer le Lien",
    "auth.checkEmail": "Vérifiez Votre E-mail",
    "auth.resetSent": "Nous avons envoyé un lien de réinitialisation à votre e-mail.",
    "auth.backToLogin": "Retour à la connexion",
    "auth.welcomeBack": "Bienvenue sur AIDoc",
    "auth.welcomeBackSubtitle": "Votre compagnon santé IA est prêt.",
    "auth.joinTitle": "Rejoignez AIDoc Aujourd'hui",
    "auth.joinSubtitle": "Obtenez des conseils santé par IA 24/7.",
    "footer.description": "Votre compagnon santé propulsé par l'IA.",
    "footer.quickLinks": "Liens Rapides",
    "footer.legal": "Mentions Légales",
    "footer.contact": "Contact",
    "footer.rights": "© 2026 AIDoc. Tous droits réservés.",
    "footer.disclaimer": "⚠️ AIDoc ne remplace pas un avis médical professionnel.",
    "admin.dashboard": "Tableau de Bord",
    "admin.welcome": "Bienvenue, Admin",
    "admin.totalUsers": "Utilisateurs Totaux",
    "admin.healthChecksToday": "Bilans Aujourd'hui",
    "admin.aiChatSessions": "Sessions Chat IA",
    "admin.criticalAlerts": "Alertes Critiques",
    "admin.users": "Utilisateurs",
    "admin.aiChats": "Chats IA",
    "admin.backToSite": "Retour au Site",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.symptomChecker": "فحص الأعراض",
    "nav.aiDoctor": "طبيب الذكاء الاصطناعي",
    "nav.healthLibrary": "مكتبة الصحة",
    "nav.about": "حول",
    "nav.login": "تسجيل الدخول",
    "nav.getStarted": "ابدأ الآن",
    "hero.badge": "ذكاء صحي مدعوم بالذكاء الاصطناعي",
    "hero.title1": "صحتك،",
    "hero.title2": "مفسّرة",
    "hero.title3": "بالذكاء الاصطناعي",
    "hero.subtitle": "تحقق من الأعراض، تحدث مع طبيب ذكاء اصطناعي، وتحكم بصحتك — من راحة منزلك.",
    "hero.checkSymptoms": "فحص الأعراض الآن",
    "hero.talkAI": "تحدث مع طبيب IA",
    "stats.healthChecks": "فحوصات صحية",
    "stats.accuracy": "معدل الدقة",
    "stats.users": "مستخدمون سعداء",
    "stats.available": "متاح",
    "features.title1": "كل ما تحتاجه من أجل",
    "features.title2": "صحة أفضل",
    "features.subtitle": "مدعوم بأحدث تقنيات الذكاء الاصطناعي",
    "cta.title": "ابدأ رحلتك الصحية اليوم",
    "cta.subtitle": "انضم لأكثر من 500,000 شخص يثقون بـ AIDoc.",
    "cta.button": "إنشاء حساب مجاني",
    "auth.signIn": "تسجيل الدخول",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "footer.rights": "© 2026 AIDoc. جميع الحقوق محفوظة.",
  },
  zh: {
    "nav.home": "首页",
    "nav.symptomChecker": "症状检查",
    "nav.aiDoctor": "AI医生",
    "nav.healthLibrary": "健康库",
    "nav.about": "关于",
    "nav.login": "登录",
    "nav.getStarted": "开始使用",
    "hero.badge": "AI驱动健康智能",
    "hero.title1": "你的健康，",
    "hero.title2": "由AI解码",
    "hero.title3": "",
    "hero.subtitle": "检查症状，与AI医生交流，掌控你的健康——一切尽在家中。",
    "hero.checkSymptoms": "立即检查症状",
    "hero.talkAI": "与AI医生对话",
    "stats.healthChecks": "健康检查",
    "stats.accuracy": "准确率",
    "stats.users": "满意用户",
    "stats.available": "全天候",
    "features.title1": "你需要的一切为了",
    "features.title2": "更好的健康",
    "features.subtitle": "由尖端AI驱动，医学研究支持",
    "cta.title": "今天开始你的健康之旅",
    "cta.subtitle": "加入超过50万信赖AIDoc的用户。",
    "cta.button": "免费创建账户",
    "auth.signIn": "登录",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "footer.rights": "© 2026 AIDoc. 版权所有。",
  },
  hi: {
    "nav.home": "होम",
    "nav.symptomChecker": "लक्षण जांच",
    "nav.aiDoctor": "AI डॉक्टर",
    "nav.healthLibrary": "स्वास्थ्य पुस्तकालय",
    "nav.about": "हमारे बारे में",
    "nav.login": "लॉगिन",
    "nav.getStarted": "शुरू करें",
    "hero.badge": "AI-संचालित स्वास्थ्य बुद्धिमत्ता",
    "hero.title1": "आपका स्वास्थ्य,",
    "hero.title2": "AI द्वारा डिकोड",
    "hero.title3": "",
    "hero.subtitle": "लक्षण जांचें, AI डॉक्टर से बात करें, और अपने स्वास्थ्य पर नियंत्रण रखें।",
    "hero.checkSymptoms": "अभी लक्षण जांचें",
    "hero.talkAI": "AI डॉक्टर से बात करें",
    "cta.title": "आज ही अपनी स्वास्थ्य यात्रा शुरू करें",
    "cta.subtitle": "5 लाख+ लोग AIDoc पर भरोसा करते हैं।",
    "cta.button": "मुफ्त खाता बनाएं",
    "auth.signIn": "साइन इन",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "footer.rights": "© 2026 AIDoc. सर्वाधिकार सुरक्षित।",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  ar: "العربية",
  zh: "中文",
  hi: "हिन्दी",
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("aidoc-lang") as Language) || "en";
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("aidoc-lang", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
export { languageNames };
